require "active_support"
require "active_support/core_ext"
require "faraday"
require "faraday_middleware"
require "json"
require "more_core_extensions/all"

require "manageiq/api/client/client"
require "manageiq/api/client/acts_as_ar_query"
require "manageiq/api/client/mixins/action_mixin"
require "manageiq/api/client/mixins/acts_as_ar_query_mixin"

require "manageiq/api/client/api"
require "manageiq/api/client/action"
require "manageiq/api/client/api_version"
require "manageiq/api/client/authentication"
require "manageiq/api/client/collection"
require "manageiq/api/client/connection"
require "manageiq/api/client/error"
require "manageiq/api/client/identity"
require "manageiq/api/client/resource"
require "manageiq/api/client/version"
